export { default as home_styles } from "./home";
export { default as request_styles } from "./request";
export { default as orders_styles } from "./orders";
export { default as global_styles } from "./global";
export { default as accounts_styles } from "./accounts";
export { default as about_styles } from "./about";
export { default as profile_styles } from "./profile";
export { default as services_styles } from "./services";
export { default as products_styles } from "./products";
